// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pheme

import (
	"go.uber.org/zap"

	"cathedral/internal/config"
)

// Injectors from wire.go:

func resolveDependencies(cfg *config.Cathedral, logger *zap.Logger) (*Cathedral, error) {
	aws := cfg.AWS
	session, err := newAWS(aws)
	if err != nil {
		return nil, err
	}
	store := cfg.Store
	quickstoreStore, err := newStore(store, session)
	if err != nil {
		return nil, err
	}
	cathedral := &Cathedral{
		Config: cfg,
		Logger: logger,
		AWS:    session,
		Store:  quickstoreStore,
	}
	return cathedral, nil
}
